' ******************************************************************************
' Created by Collin Brockman 12/10/2024
' Make Selected Dimensions Decimal Document Places
' ******************************************************************************
'Start Function no Parameters in or out
Option Explicit
Dim boolstatus As Boolean
Dim intstatus As Integer
Sub main()
    'Initalize App and File to current instance
    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc
    
    Dim swSelMgr As SldWorks.SelectionMgr
    Set swSelMgr = swModel.SelectionManager
    Dim i As Integer
    For i = 0 To swSelMgr.GetSelectedObjectCount2(-1)
        If swSelMgr.GetSelectedObjectType3(i, -1) = swSelectType_e.swSelDIMENSIONS Then
            'Set to Reference Dimension
            Dim swDispDim As SldWorks.DisplayDimension
            Set swDispDim = swSelMgr.GetSelectedObject6(i, -1)
            If Not swDispDim.Type2 = swDimensionType_e.swAngularDimension Then
                intstatus = swDispDim.SetUnits2(False, swLengthUnit_e.swINCHES, swFractionDisplay_e.swDECIMAL, 0, True, swUnitsDecimalRounding_e.swUnitsDecimalRounding_HalfToEven)
        End If
        End If
    Next
    swModel.ClearSelection2 (True)
End Sub